"""
Self Help Groups and members per district.

Generated by scripts/fetch_shg_density.py — do not hand-edit.
Source: data.gov.in resource d4206736-a28b-4552-8900-7e0c23c707ac
Counts are de-duplicated to each village's most recent financial year.
"""

SHG_BY_DISTRICT = {
    "Bihar": {
        "Araria": {
            "members": 21903,
            "shgs": 2611,
            "villages": 690,
            "villages_with_shg": 339
        },
        "Arwal": {
            "members": 5056,
            "shgs": 426,
            "villages": 294,
            "villages_with_shg": 167
        },
        "Aurangabad": {
            "members": 4751,
            "shgs": 440,
            "villages": 1625,
            "villages_with_shg": 202
        },
        "Banka": {
            "members": 4625,
            "shgs": 467,
            "villages": 1453,
            "villages_with_shg": 220
        },
        "Begusarai": {
            "members": 17541,
            "shgs": 1638,
            "villages": 680,
            "villages_with_shg": 312
        },
        "Bhagalpur": {
            "members": 23523,
            "shgs": 2444,
            "villages": 996,
            "villages_with_shg": 501
        },
        "Bhojpur": {
            "members": 14692,
            "shgs": 1312,
            "villages": 971,
            "villages_with_shg": 450
        },
        "Buxar": {
            "members": 2141,
            "shgs": 222,
            "villages": 736,
            "villages_with_shg": 108
        },
        "Darbhanga": {
            "members": 15253,
            "shgs": 1495,
            "villages": 1017,
            "villages_with_shg": 405
        },
        "East Champaran": {
            "members": 16622,
            "shgs": 1743,
            "villages": 1272,
            "villages_with_shg": 483
        },
        "Gaya": {
            "members": 20007,
            "shgs": 1317,
            "villages": 2479,
            "villages_with_shg": 467
        },
        "Gopalganj": {
            "members": 3604,
            "shgs": 357,
            "villages": 1297,
            "villages_with_shg": 179
        },
        "Jamui": {
            "members": 3005,
            "shgs": 265,
            "villages": 1139,
            "villages_with_shg": 114
        },
        "Jehanabad": {
            "members": 574,
            "shgs": 56,
            "villages": 533,
            "villages_with_shg": 36
        },
        "Kaimur": {
            "members": 11565,
            "shgs": 1101,
            "villages": 1184,
            "villages_with_shg": 420
        },
        "Katihar": {
            "members": 13422,
            "shgs": 1358,
            "villages": 1156,
            "villages_with_shg": 369
        },
        "Khagaria": {
            "members": 9884,
            "shgs": 948,
            "villages": 259,
            "villages_with_shg": 158
        },
        "Kishanganj": {
            "members": 3418,
            "shgs": 326,
            "villages": 649,
            "villages_with_shg": 135
        },
        "Lakhisarai": {
            "members": 3821,
            "shgs": 383,
            "villages": 334,
            "villages_with_shg": 119
        },
        "Madhepura": {
            "members": 8409,
            "shgs": 926,
            "villages": 382,
            "villages_with_shg": 198
        },
        "Madhubani": {
            "members": 2761,
            "shgs": 295,
            "villages": 1022,
            "villages_with_shg": 106
        },
        "Munger": {
            "members": 6466,
            "shgs": 686,
            "villages": 496,
            "villages_with_shg": 209
        },
        "Muzaffarpur": {
            "members": 17236,
            "shgs": 1765,
            "villages": 1604,
            "villages_with_shg": 500
        },
        "Nalanda": {
            "members": 3735,
            "shgs": 367,
            "villages": 967,
            "villages_with_shg": 185
        },
        "Nawada": {
            "members": 6974,
            "shgs": 670,
            "villages": 951,
            "villages_with_shg": 245
        },
        "Patna": {
            "members": 15527,
            "shgs": 1570,
            "villages": 1257,
            "villages_with_shg": 480
        },
        "Purnia": {
            "members": 3517,
            "shgs": 335,
            "villages": 919,
            "villages_with_shg": 120
        },
        "Rohtas": {
            "members": 3886,
            "shgs": 399,
            "villages": 1615,
            "villages_with_shg": 221
        },
        "Saharsa": {
            "members": 32654,
            "shgs": 3866,
            "villages": 441,
            "villages_with_shg": 357
        },
        "Samastipur": {
            "members": 13175,
            "shgs": 1228,
            "villages": 1094,
            "villages_with_shg": 313
        },
        "Saran": {
            "members": 12548,
            "shgs": 1350,
            "villages": 1468,
            "villages_with_shg": 399
        },
        "Sheikhpura": {
            "members": 3016,
            "shgs": 322,
            "villages": 254,
            "villages_with_shg": 109
        },
        "Sheohar": {
            "members": 898,
            "shgs": 90,
            "villages": 190,
            "villages_with_shg": 39
        },
        "Sitamarhi": {
            "members": 5984,
            "shgs": 551,
            "villages": 808,
            "villages_with_shg": 171
        },
        "Siwan": {
            "members": 1047,
            "shgs": 108,
            "villages": 1338,
            "villages_with_shg": 56
        },
        "Supaul": {
            "members": 12245,
            "shgs": 1203,
            "villages": 504,
            "villages_with_shg": 212
        },
        "Vaishali": {
            "members": 14868,
            "shgs": 1445,
            "villages": 1287,
            "villages_with_shg": 450
        },
        "West Champaran": {
            "members": 10518,
            "shgs": 1137,
            "villages": 1324,
            "villages_with_shg": 363
        }
    },
    "Kerala": {
        "Alappuzha": {
            "members": 806,
            "shgs": 44,
            "villages": 1171,
            "villages_with_shg": 32
        },
        "Ernakulam": {
            "members": 279,
            "shgs": 19,
            "villages": 1338,
            "villages_with_shg": 19
        },
        "Idukki": {
            "members": 620,
            "shgs": 39,
            "villages": 788,
            "villages_with_shg": 30
        },
        "Kannur": {
            "members": 520,
            "shgs": 32,
            "villages": 1169,
            "villages_with_shg": 28
        },
        "Kasargod": {
            "members": 474,
            "shgs": 25,
            "villages": 666,
            "villages_with_shg": 21
        },
        "Kollam": {
            "members": 1296,
            "shgs": 76,
            "villages": 1235,
            "villages_with_shg": 65
        },
        "Kottayam": {
            "members": 399,
            "shgs": 26,
            "villages": 1141,
            "villages_with_shg": 25
        },
        "Kozhikode": {
            "members": 461,
            "shgs": 29,
            "villages": 1227,
            "villages_with_shg": 26
        },
        "Malappuram": {
            "members": 2129,
            "shgs": 98,
            "villages": 1779,
            "villages_with_shg": 82
        },
        "Palakkad": {
            "members": 1067,
            "shgs": 71,
            "villages": 1488,
            "villages_with_shg": 52
        },
        "Pathanamthitta": {
            "members": 206,
            "shgs": 11,
            "villages": 788,
            "villages_with_shg": 11
        },
        "Thiruvananthapuram": {
            "members": 1748,
            "shgs": 88,
            "villages": 1300,
            "villages_with_shg": 71
        },
        "Thrissur": {
            "members": 281,
            "shgs": 18,
            "villages": 1465,
            "villages_with_shg": 18
        },
        "Wayanad": {
            "members": 1153,
            "shgs": 66,
            "villages": 414,
            "villages_with_shg": 49
        }
    },
    "Maharashtra": {
        "Ahmednagar": {
            "members": 51413,
            "shgs": 4700,
            "villages": 1429,
            "villages_with_shg": 768
        },
        "Akola": {
            "members": 550,
            "shgs": 53,
            "villages": 788,
            "villages_with_shg": 40
        },
        "Amravati": {
            "members": 2852,
            "shgs": 222,
            "villages": 1426,
            "villages_with_shg": 136
        },
        "Aurangabad": {
            "members": 22144,
            "shgs": 1919,
            "villages": 1112,
            "villages_with_shg": 430
        },
        "Beed": {
            "members": 2062,
            "shgs": 170,
            "villages": 1306,
            "villages_with_shg": 97
        },
        "Bhandara": {
            "members": 762,
            "shgs": 62,
            "villages": 747,
            "villages_with_shg": 43
        },
        "Buldhana": {
            "members": 713,
            "shgs": 66,
            "villages": 1200,
            "villages_with_shg": 48
        },
        "Chandrapur": {
            "members": 3253,
            "shgs": 264,
            "villages": 1432,
            "villages_with_shg": 189
        },
        "Dhule": {
            "members": 2198,
            "shgs": 172,
            "villages": 660,
            "villages_with_shg": 103
        },
        "Gadchiroli": {
            "members": 670,
            "shgs": 59,
            "villages": 1379,
            "villages_with_shg": 45
        },
        "Gondia": {
            "members": 2133,
            "shgs": 174,
            "villages": 872,
            "villages_with_shg": 93
        },
        "Hingoli": {
            "members": 2735,
            "shgs": 239,
            "villages": 631,
            "villages_with_shg": 126
        },
        "Jalgaon": {
            "members": 3136,
            "shgs": 292,
            "villages": 1437,
            "villages_with_shg": 164
        },
        "Jalna": {
            "members": 1310,
            "shgs": 99,
            "villages": 923,
            "villages_with_shg": 58
        },
        "Kolhapur": {
            "members": 8275,
            "shgs": 757,
            "villages": 1176,
            "villages_with_shg": 336
        },
        "Latur": {
            "members": 1401,
            "shgs": 122,
            "villages": 910,
            "villages_with_shg": 90
        },
        "Nagpur": {
            "members": 1593,
            "shgs": 145,
            "villages": 1473,
            "villages_with_shg": 78
        },
        "Nanded": {
            "members": 3487,
            "shgs": 316,
            "villages": 1479,
            "villages_with_shg": 192
        },
        "Nandurbar": {
            "members": 1424,
            "shgs": 101,
            "villages": 924,
            "villages_with_shg": 75
        },
        "Nashik": {
            "members": 4428,
            "shgs": 390,
            "villages": 1851,
            "villages_with_shg": 213
        },
        "Osmanabad": {
            "members": 4646,
            "shgs": 338,
            "villages": 649,
            "villages_with_shg": 116
        },
        "Palghar": {
            "members": 1693,
            "shgs": 139,
            "villages": 890,
            "villages_with_shg": 84
        },
        "Parbhani": {
            "members": 2126,
            "shgs": 212,
            "villages": 780,
            "villages_with_shg": 143
        },
        "Pune": {
            "members": 4868,
            "shgs": 426,
            "villages": 1736,
            "villages_with_shg": 218
        },
        "Raigad": {
            "members": 2736,
            "shgs": 252,
            "villages": 1792,
            "villages_with_shg": 155
        },
        "Ratnagiri": {
            "members": 834,
            "shgs": 70,
            "villages": 1427,
            "villages_with_shg": 54
        },
        "Sangli": {
            "members": 4704,
            "shgs": 406,
            "villages": 713,
            "villages_with_shg": 188
        },
        "Satara": {
            "members": 3422,
            "shgs": 290,
            "villages": 1581,
            "villages_with_shg": 166
        },
        "Sindhudurg": {
            "members": 153,
            "shgs": 13,
            "villages": 726,
            "villages_with_shg": 9
        },
        "Solapur": {
            "members": 2521,
            "shgs": 211,
            "villages": 1106,
            "villages_with_shg": 112
        },
        "Thane": {
            "members": 507,
            "shgs": 44,
            "villages": 768,
            "villages_with_shg": 33
        },
        "Wardha": {
            "members": 771,
            "shgs": 61,
            "villages": 863,
            "villages_with_shg": 44
        },
        "Washim": {
            "members": 635,
            "shgs": 65,
            "villages": 680,
            "villages_with_shg": 51
        },
        "Yavatmal": {
            "members": 2700,
            "shgs": 212,
            "villages": 1727,
            "villages_with_shg": 145
        }
    },
    "Odisha": {
        "Angul": {
            "members": 3316,
            "shgs": 267,
            "villages": 1448,
            "villages_with_shg": 149
        },
        "Balasore": {
            "members": 6957,
            "shgs": 540,
            "villages": 2388,
            "villages_with_shg": 303
        },
        "Bargarh": {
            "members": 8046,
            "shgs": 666,
            "villages": 1163,
            "villages_with_shg": 184
        },
        "Bhadrak": {
            "members": 2939,
            "shgs": 240,
            "villages": 1164,
            "villages_with_shg": 149
        },
        "Bolangir": {
            "members": 3208,
            "shgs": 280,
            "villages": 1716,
            "villages_with_shg": 163
        },
        "Boudh": {
            "members": 388,
            "shgs": 36,
            "villages": 956,
            "villages_with_shg": 28
        },
        "Cuttack": {
            "members": 3959,
            "shgs": 310,
            "villages": 1778,
            "villages_with_shg": 165
        },
        "Deogarh": {
            "members": 487,
            "shgs": 41,
            "villages": 650,
            "villages_with_shg": 37
        },
        "Dhenkanal": {
            "members": 7038,
            "shgs": 690,
            "villages": 959,
            "villages_with_shg": 155
        },
        "Gajapati": {
            "members": 541,
            "shgs": 45,
            "villages": 1362,
            "villages_with_shg": 31
        },
        "Ganjam": {
            "members": 7835,
            "shgs": 637,
            "villages": 2318,
            "villages_with_shg": 272
        },
        "Jagatsinghapur": {
            "members": 1769,
            "shgs": 155,
            "villages": 1163,
            "villages_with_shg": 106
        },
        "Jajpur": {
            "members": 5200,
            "shgs": 369,
            "villages": 1492,
            "villages_with_shg": 179
        },
        "Jharsuguda": {
            "members": 484,
            "shgs": 44,
            "villages": 338,
            "villages_with_shg": 21
        },
        "Kalahandi": {
            "members": 2440,
            "shgs": 209,
            "villages": 1882,
            "villages_with_shg": 146
        },
        "Kandhamal": {
            "members": 1552,
            "shgs": 127,
            "villages": 1892,
            "villages_with_shg": 74
        },
        "Kendrapara": {
            "members": 4288,
            "shgs": 309,
            "villages": 1331,
            "villages_with_shg": 177
        },
        "Keonjhar": {
            "members": 6057,
            "shgs": 454,
            "villages": 1960,
            "villages_with_shg": 255
        },
        "Khordha": {
            "members": 1870,
            "shgs": 159,
            "villages": 1228,
            "villages_with_shg": 89
        },
        "Koraput": {
            "members": 2220,
            "shgs": 184,
            "villages": 1666,
            "villages_with_shg": 104
        },
        "Malkangiri": {
            "members": 2066,
            "shgs": 153,
            "villages": 746,
            "villages_with_shg": 85
        },
        "Mayurbhanj": {
            "members": 22917,
            "shgs": 1692,
            "villages": 3659,
            "villages_with_shg": 697
        },
        "Nabarangapur": {
            "members": 2185,
            "shgs": 165,
            "villages": 848,
            "villages_with_shg": 101
        },
        "Nayagarh": {
            "members": 3383,
            "shgs": 288,
            "villages": 1317,
            "villages_with_shg": 176
        },
        "Nuapada": {
            "members": 1015,
            "shgs": 87,
            "villages": 601,
            "villages_with_shg": 59
        },
        "Puri": {
            "members": 4028,
            "shgs": 271,
            "villages": 1523,
            "villages_with_shg": 113
        },
        "Rayagada": {
            "members": 2230,
            "shgs": 185,
            "villages": 2085,
            "villages_with_shg": 110
        },
        "Sambalpur": {
            "members": 726,
            "shgs": 60,
            "villages": 1124,
            "villages_with_shg": 37
        },
        "Subarnapur": {
            "members": 1253,
            "shgs": 113,
            "villages": 781,
            "villages_with_shg": 75
        },
        "Sundargarh": {
            "members": 2634,
            "shgs": 200,
            "villages": 1589,
            "villages_with_shg": 116
        }
    },
    "Rajasthan": {
        "Ajmer": {
            "members": 761,
            "shgs": 66,
            "villages": 971,
            "villages_with_shg": 33
        },
        "Alwar": {
            "members": 3063,
            "shgs": 288,
            "villages": 1535,
            "villages_with_shg": 120
        },
        "Banswara": {
            "members": 1483,
            "shgs": 153,
            "villages": 1428,
            "villages_with_shg": 60
        },
        "Baran": {
            "members": 826,
            "shgs": 82,
            "villages": 1007,
            "villages_with_shg": 42
        },
        "Barmer": {
            "members": 2633,
            "shgs": 335,
            "villages": 2161,
            "villages_with_shg": 143
        },
        "Bharatpur": {
            "members": 636,
            "shgs": 50,
            "villages": 1196,
            "villages_with_shg": 28
        },
        "Bhilwara": {
            "members": 158,
            "shgs": 15,
            "villages": 1605,
            "villages_with_shg": 12
        },
        "Bikaner": {
            "members": 27,
            "shgs": 3,
            "villages": 697,
            "villages_with_shg": 2
        },
        "Bundi": {
            "members": 2116,
            "shgs": 239,
            "villages": 817,
            "villages_with_shg": 124
        },
        "Chittor": {
            "members": 127,
            "shgs": 14,
            "villages": 1338,
            "villages_with_shg": 9
        },
        "Churu": {
            "members": 278,
            "shgs": 40,
            "villages": 806,
            "villages_with_shg": 23
        },
        "Dausa": {
            "members": 855,
            "shgs": 87,
            "villages": 882,
            "villages_with_shg": 49
        },
        "Dholpur": {
            "members": 48,
            "shgs": 5,
            "villages": 713,
            "villages_with_shg": 4
        },
        "Dungarpur": {
            "members": 4312,
            "shgs": 479,
            "villages": 939,
            "villages_with_shg": 185
        },
        "Ganganagar": {
            "members": 717,
            "shgs": 86,
            "villages": 1520,
            "villages_with_shg": 56
        },
        "Hanumangarh": {
            "members": 5737,
            "shgs": 597,
            "villages": 923,
            "villages_with_shg": 213
        },
        "Jaipur": {
            "members": 821,
            "shgs": 91,
            "villages": 1741,
            "villages_with_shg": 47
        },
        "Jaisalmer": {
            "members": 20,
            "shgs": 2,
            "villages": 501,
            "villages_with_shg": 1
        },
        "Jalore": {
            "members": 12,
            "shgs": 2,
            "villages": 709,
            "villages_with_shg": 2
        },
        "Jhalawar": {
            "members": 287,
            "shgs": 24,
            "villages": 1341,
            "villages_with_shg": 19
        },
        "Jhunjhunu": {
            "members": 122,
            "shgs": 16,
            "villages": 739,
            "villages_with_shg": 15
        },
        "Jodhpur": {
            "members": 9,
            "shgs": 1,
            "villages": 1368,
            "villages_with_shg": 1
        },
        "Karauli": {
            "members": 545,
            "shgs": 58,
            "villages": 785,
            "villages_with_shg": 28
        },
        "Kota": {
            "members": 773,
            "shgs": 49,
            "villages": 724,
            "villages_with_shg": 29
        },
        "Nagaur": {
            "members": 1693,
            "shgs": 174,
            "villages": 1323,
            "villages_with_shg": 70
        },
        "Pali": {
            "members": 2098,
            "shgs": 167,
            "villages": 944,
            "villages_with_shg": 67
        },
        "Pratapgarh": {
            "members": 533,
            "shgs": 70,
            "villages": 856,
            "villages_with_shg": 36
        },
        "Sawai Madhopur": {
            "members": 206,
            "shgs": 12,
            "villages": 680,
            "villages_with_shg": 1
        },
        "Sikar": {
            "members": 91,
            "shgs": 10,
            "villages": 930,
            "villages_with_shg": 7
        },
        "Sirohi": {
            "members": 109,
            "shgs": 3,
            "villages": 432,
            "villages_with_shg": 1
        },
        "Tonk": {
            "members": 175,
            "shgs": 20,
            "villages": 934,
            "villages_with_shg": 8
        },
        "Udaipur": {
            "members": 142,
            "shgs": 15,
            "villages": 2214,
            "villages_with_shg": 7
        }
    },
    "Uttar Pradesh": {
        "Agra": {
            "members": 404,
            "shgs": 26,
            "villages": 1054,
            "villages_with_shg": 20
        },
        "Aligarh": {
            "members": 484,
            "shgs": 34,
            "villages": 1151,
            "villages_with_shg": 24
        },
        "Ambedkar Nagar": {
            "members": 367,
            "shgs": 25,
            "villages": 1572,
            "villages_with_shg": 22
        },
        "Amethi": {
            "members": 864,
            "shgs": 94,
            "villages": 912,
            "villages_with_shg": 65
        },
        "Amroha": {
            "members": 564,
            "shgs": 47,
            "villages": 848,
            "villages_with_shg": 39
        },
        "Auraiya": {
            "members": 562,
            "shgs": 49,
            "villages": 926,
            "villages_with_shg": 35
        },
        "Ayodhya": {
            "members": 2827,
            "shgs": 218,
            "villages": 1108,
            "villages_with_shg": 138
        },
        "Azamgarh": {
            "members": 1918,
            "shgs": 166,
            "villages": 2890,
            "villages_with_shg": 102
        },
        "Baghpat": {
            "members": 102,
            "shgs": 7,
            "villages": 280,
            "villages_with_shg": 7
        },
        "Bahraich": {
            "members": 688,
            "shgs": 63,
            "villages": 1802,
            "villages_with_shg": 47
        },
        "Ballia": {
            "members": 1811,
            "shgs": 139,
            "villages": 1445,
            "villages_with_shg": 104
        },
        "Balrampur": {
            "members": 1473,
            "shgs": 142,
            "villages": 977,
            "villages_with_shg": 63
        },
        "Banda": {
            "members": 1093,
            "shgs": 105,
            "villages": 626,
            "villages_with_shg": 62
        },
        "Barabanki": {
            "members": 2415,
            "shgs": 234,
            "villages": 1747,
            "villages_with_shg": 152
        },
        "Bareilly": {
            "members": 2409,
            "shgs": 197,
            "villages": 1529,
            "villages_with_shg": 137
        },
        "Basti": {
            "members": 1916,
            "shgs": 162,
            "villages": 2590,
            "villages_with_shg": 99
        },
        "Bijnor": {
            "members": 1379,
            "shgs": 110,
            "villages": 1808,
            "villages_with_shg": 82
        },
        "Budaun": {
            "members": 587,
            "shgs": 54,
            "villages": 1536,
            "villages_with_shg": 43
        },
        "Bulandshahar": {
            "members": 1247,
            "shgs": 101,
            "villages": 1174,
            "villages_with_shg": 79
        },
        "Chandauli": {
            "members": 2330,
            "shgs": 225,
            "villages": 1182,
            "villages_with_shg": 174
        },
        "ChitraKoot": {
            "members": 282,
            "shgs": 24,
            "villages": 567,
            "villages_with_shg": 20
        },
        "Deoria": {
            "members": 383,
            "shgs": 32,
            "villages": 1833,
            "villages_with_shg": 28
        },
        "Etah": {
            "members": 392,
            "shgs": 26,
            "villages": 912,
            "villages_with_shg": 19
        },
        "Etawah": {
            "members": 296,
            "shgs": 27,
            "villages": 680,
            "villages_with_shg": 25
        },
        "Farrukhabad": {
            "members": 744,
            "shgs": 62,
            "villages": 815,
            "villages_with_shg": 47
        },
        "Fatehpur": {
            "members": 1357,
            "shgs": 131,
            "villages": 1312,
            "villages_with_shg": 71
        },
        "Firozabad": {
            "members": 1614,
            "shgs": 140,
            "villages": 741,
            "villages_with_shg": 91
        },
        "G. B. Nagar": {
            "members": 9,
            "shgs": 1,
            "villages": 156,
            "villages_with_shg": 1
        },
        "Ghaziabad": {
            "members": 32,
            "shgs": 2,
            "villages": 174,
            "villages_with_shg": 2
        },
        "Ghazipur": {
            "members": 2093,
            "shgs": 202,
            "villages": 2598,
            "villages_with_shg": 159
        },
        "Gonda": {
            "members": 2381,
            "shgs": 235,
            "villages": 1502,
            "villages_with_shg": 135
        },
        "Gorakhpur": {
            "members": 415,
            "shgs": 34,
            "villages": 2299,
            "villages_with_shg": 29
        },
        "Hamirpur": {
            "members": 153,
            "shgs": 13,
            "villages": 479,
            "villages_with_shg": 11
        },
        "Hapur": {
            "members": 234,
            "shgs": 16,
            "villages": 305,
            "villages_with_shg": 14
        },
        "Hardoi": {
            "members": 4507,
            "shgs": 470,
            "villages": 1783,
            "villages_with_shg": 256
        },
        "Hathras": {
            "members": 437,
            "shgs": 37,
            "villages": 779,
            "villages_with_shg": 27
        },
        "Jalaun": {
            "members": 661,
            "shgs": 46,
            "villages": 876,
            "villages_with_shg": 39
        },
        "Jaunpur": {
            "members": 5273,
            "shgs": 426,
            "villages": 2661,
            "villages_with_shg": 283
        },
        "Jhansi": {
            "members": 498,
            "shgs": 38,
            "villages": 710,
            "villages_with_shg": 34
        },
        "Kannauj": {
            "members": 1403,
            "shgs": 107,
            "villages": 641,
            "villages_with_shg": 78
        },
        "Kanpur Nagar": {
            "members": 719,
            "shgs": 62,
            "villages": 835,
            "villages_with_shg": 47
        },
        "Kasganj": {
            "members": 798,
            "shgs": 72,
            "villages": 607,
            "villages_with_shg": 57
        },
        "Kaushambi": {
            "members": 3890,
            "shgs": 385,
            "villages": 634,
            "villages_with_shg": 233
        },
        "Kushinagar": {
            "members": 6572,
            "shgs": 652,
            "villages": 1368,
            "villages_with_shg": 333
        },
        "Lakhimpur Kheri": {
            "members": 1444,
            "shgs": 116,
            "villages": 1630,
            "villages_with_shg": 78
        },
        "Lalitpur": {
            "members": 331,
            "shgs": 28,
            "villages": 619,
            "villages_with_shg": 23
        },
        "Lucknow": {
            "members": 1170,
            "shgs": 95,
            "villages": 905,
            "villages_with_shg": 66
        },
        "Maharajganj": {
            "members": 2101,
            "shgs": 157,
            "villages": 1050,
            "villages_with_shg": 109
        },
        "Mahoba": {
            "members": 193,
            "shgs": 19,
            "villages": 410,
            "villages_with_shg": 9
        },
        "Mainpuri": {
            "members": 243,
            "shgs": 16,
            "villages": 763,
            "villages_with_shg": 13
        },
        "Mathura": {
            "members": 878,
            "shgs": 63,
            "villages": 632,
            "villages_with_shg": 47
        },
        "Mau": {
            "members": 1094,
            "shgs": 102,
            "villages": 1117,
            "villages_with_shg": 63
        },
        "Meerut": {
            "members": 340,
            "shgs": 27,
            "villages": 527,
            "villages_with_shg": 18
        },
        "Mirzapur": {
            "members": 1883,
            "shgs": 144,
            "villages": 1466,
            "villages_with_shg": 83
        },
        "Moradabad": {
            "members": 654,
            "shgs": 61,
            "villages": 920,
            "villages_with_shg": 40
        },
        "Muzaffarnagar": {
            "members": 428,
            "shgs": 37,
            "villages": 546,
            "villages_with_shg": 29
        },
        "Pilibhit": {
            "members": 6356,
            "shgs": 700,
            "villages": 1067,
            "villages_with_shg": 216
        },
        "Pratapgarh": {
            "members": 1842,
            "shgs": 157,
            "villages": 1954,
            "villages_with_shg": 140
        },
        "Prayagraj": {
            "members": 6186,
            "shgs": 453,
            "villages": 2541,
            "villages_with_shg": 269
        },
        "Rae Bareli": {
            "members": 4201,
            "shgs": 385,
            "villages": 1459,
            "villages_with_shg": 226
        },
        "Rampur": {
            "members": 483,
            "shgs": 42,
            "villages": 913,
            "villages_with_shg": 32
        },
        "Saharanpur": {
            "members": 676,
            "shgs": 57,
            "villages": 1098,
            "villages_with_shg": 46
        },
        "Sambhal": {
            "members": 763,
            "shgs": 70,
            "villages": 859,
            "villages_with_shg": 50
        },
        "Sant Kabir Nagar": {
            "members": 473,
            "shgs": 39,
            "villages": 1289,
            "villages_with_shg": 33
        },
        "Shahjahanpur": {
            "members": 1122,
            "shgs": 95,
            "villages": 1803,
            "villages_with_shg": 70
        },
        "Shamali": {
            "members": 67,
            "shgs": 7,
            "villages": 265,
            "villages_with_shg": 7
        },
        "Shrawasti": {
            "members": 1610,
            "shgs": 147,
            "villages": 493,
            "villages_with_shg": 71
        },
        "Siddharthnagar": {
            "members": 653,
            "shgs": 61,
            "villages": 1869,
            "villages_with_shg": 57
        },
        "Sitapur": {
            "members": 2225,
            "shgs": 217,
            "villages": 2169,
            "villages_with_shg": 130
        },
        "Sonbhadra": {
            "members": 584,
            "shgs": 49,
            "villages": 1237,
            "villages_with_shg": 38
        },
        "Sultanpur": {
            "members": 453,
            "shgs": 34,
            "villages": 1561,
            "villages_with_shg": 32
        },
        "Unnao": {
            "members": 1148,
            "shgs": 83,
            "villages": 1568,
            "villages_with_shg": 60
        },
        "Varanasi": {
            "members": 1811,
            "shgs": 121,
            "villages": 1061,
            "villages_with_shg": 84
        }
    }
}
