"""
The share of a pincode's enterprises each trade normally has.

Generated by scripts/fetch_trade_baseline.py — do not hand-edit.
Median across 47 sampled pincodes in six states.
Used to tell 'unusually few here' apart from 'this is simply a
small trade everywhere', which a raw count cannot do.
"""

TRADE_BASELINE = {
    "agarbatti": {
        "samples": 47,
        "typical_share": 0.0
    },
    "beekeeping": {
        "samples": 47,
        "typical_share": 0.1177
    },
    "dairy": {
        "samples": 47,
        "typical_share": 1.4909
    },
    "handcraft": {
        "samples": 47,
        "typical_share": 0.7257
    },
    "pickle": {
        "samples": 47,
        "typical_share": 0.2828
    },
    "poultry": {
        "samples": 47,
        "typical_share": 0.6108
    },
    "soap": {
        "samples": 47,
        "typical_share": 0.0677
    },
    "tailoring": {
        "samples": 47,
        "typical_share": 2.1186
    },
    "weaving": {
        "samples": 47,
        "typical_share": 0.1871
    }
}

SAMPLED_PINCODES = 47
