"""
What trades people actually run in her pincode — not just the ten we researched.

The ten skills in data/skills.py were chosen in advance and they are all
production trades: make a thing, sell the thing. Measured against the register,
they account for about 22% of the enterprises in a rural pincode. The other 78%
is shopkeeping, food service and personal services — the trades rural women
most commonly actually run, and the catalogue could not see any of them.

This reads her pincode and reports what is really there. Two things it is
careful about:

  The counts are real and the names are not. Every number here comes from the
  Udyam register. The human-readable names come from a language model, because
  the register writes things like "General household maintenance activities
  like grooming of the floor" and a woman needs to read "घर की साफ़-सफ़ाई का
  काम". The model groups and names; it never invents a count.

  A discovered trade is not an assessed trade. The ten researched skills carry
  entry costs, equipment lists, supply chains, requirement thresholds and
  schemes, all from documented research. A trade discovered here carries none
  of that, and no model should be asked to supply it — a plausible-sounding
  "entry cost Rs 25,000" generated by an 8B model is a fabrication wearing the
  clothes of research. So discovered trades are offered as things that
  demonstrably work locally, assessed only against what we can honestly judge:
  her capital, space, hours, market access and group.
"""
import collections
import json
import logging
import pathlib
import re

import requests

from data.nic_trades import NIC_BY_SKILL
from logic.local_market import HEADERS, api_key, looks_like_pincode

log = logging.getLogger(__name__)

RESOURCE = "8b68ae56-84cf-4728-a0a6-1be11028dea7"
BASE = f"https://api.data.gov.in/resource/{RESOURCE}"
PAGE = 1000
MAX_PAGES = 6

CACHE_DIR = pathlib.Path(__file__).resolve().parent.parent / "data" / "discovery_cache"

# Codes for trades the ten skills already cover, so discovery offers her
# something new rather than repeating what the engine already assesses properly.
ALREADY_MODELLED = {code for codes in NIC_BY_SKILL.values() for code in codes}

# Whole NIC divisions that are not a home enterprise a woman could start from
# her village: motor trade, transport, finance, public administration,
# education, health, mining, utilities, construction. Excluded by division
# rather than by guessing at individual codes.
NOT_A_HOME_TRADE = {
    "05", "06", "07", "08", "09",        # mining
    "19", "24", "25", "29", "30",        # heavy manufacturing, vehicles
    "35", "36", "37", "38", "39",        # utilities, waste
    "41", "42", "43",                    # construction
    "45",                                # motor vehicle trade
    "49", "50", "51", "52", "53",        # transport and storage
    "64", "65", "66",                    # finance and insurance
    "68", "69", "71", "72", "75",        # real estate, legal, research, vets
    "77", "78", "79", "80", "84",        # renting, employment, security, govt
    "85", "86", "87", "88",              # education, health, social work
    "97", "98", "99",                    # households as employers
}

MIN_LOCAL_COUNT = 8   # below this the trade is too rare here to suggest


def _cache_path(pincode):
    return CACHE_DIR / f"{pincode}.json"


def local_activity(pincode, key=None):
    """
    Every NIC code in her pincode with its count and the register's wording.

    Cached, and separate from the trade counts cache because this keeps the
    full tail of 700-odd codes rather than only the ten we model.
    """
    if not looks_like_pincode(pincode):
        return None
    pincode = str(pincode).strip()

    try:
        return json.loads(_cache_path(pincode).read_text())
    except Exception:
        pass

    key = key or api_key()
    if not key:
        return None

    tally, wording, scanned = collections.Counter(), {}, 0
    for page in range(MAX_PAGES):
        params = {"api-key": key, "format": "json", "limit": PAGE,
                  "offset": page * PAGE, "filters[Pincode]": pincode}
        try:
            response = requests.get(BASE, params=params, headers=HEADERS, timeout=60)
            response.raise_for_status()
            records = response.json().get("records", [])
        except Exception as exc:
            log.warning("Discovery for %s failed: %s", pincode, exc)
            return None
        if not records:
            break
        scanned += len(records)
        for record in records:
            activities = record.get("Activities")
            if isinstance(activities, str):
                try:
                    activities = json.loads(activities)
                except Exception:
                    continue
            for entry in activities or []:
                code = entry.get("NIC5DigitId")
                if not code:
                    continue
                tally[code] += 1
                wording.setdefault(code, (entry.get("Description") or "").strip())
        if len(records) < PAGE:
            break

    payload = {"pincode": pincode, "scanned": scanned,
               "counts": dict(tally), "wording": wording}
    try:
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        _cache_path(pincode).write_text(json.dumps(payload, indent=2))
    except Exception as exc:
        log.warning("Could not cache discovery for %s: %s", pincode, exc)
    return payload


def candidate_trades(pincode, limit=25, key=None):
    """
    The trades worth offering her, commonest first.

    Filtered to what could plausibly be run from a village home — whole NIC
    divisions like mining, construction and banking are dropped — and to codes
    the ten researched skills do not already cover, since those are assessed
    properly elsewhere.

    Returns raw register rows. Naming them is a separate step, because that is
    a language problem and this is a counting one.
    """
    data = local_activity(pincode, key)
    if not data or not data.get("scanned"):
        return []

    rows = []
    for code, count in data["counts"].items():
        if code in ALREADY_MODELLED or code[:2] in NOT_A_HOME_TRADE:
            continue
        if count < MIN_LOCAL_COUNT:
            continue
        rows.append({
            "code": code,
            "count": count,
            "share": count / data["scanned"],
            "register_wording": data["wording"].get(code, ""),
        })
    rows.sort(key=lambda r: -r["count"])
    return rows[:limit]


_GROUPING_SYSTEM = (
    "You are helping name rural micro-businesses for women in India who read Hindi.\n"
    "You will be given official register categories with their codes.\n"
    "Group codes that are the same kind of work into one trade, and give each group a "
    "short plain name a village woman would recognise, in Hindi and in English.\n"
    "Rules: use only the codes given; never invent a code; never mention numbers or counts; "
    "keep names under six words; prefer everyday words over official ones "
    "(say 'किराना दुकान / small grocery shop', not 'retail sale in non-specialized stores').\n"
    'Reply with JSON only: {"trades":[{"hindi":"...","english":"...","codes":["47110","47190"]}]}'
)


def _parse_possibly_truncated(raw):
    """
    Read the model's JSON, salvaging a reply that was cut off mid-array.

    An 8B model asked for two dozen groups will sometimes stop before the
    closing braces. Everything it did finish is still perfectly good, so rather
    than discard the lot, complete entries are recovered one at a time.
    """
    match = re.search(r"\{.*\}", raw, re.S)
    if match:
        try:
            return json.loads(match.group(0))
        except Exception:
            pass

    # Salvage: pull out each finished {...} object inside the trades array.
    objects = re.findall(r'\{[^{}]*"codes"\s*:\s*\[[^\]]*\][^{}]*\}', raw, re.S)
    trades = []
    for blob in objects:
        try:
            trades.append(json.loads(blob))
        except Exception:
            continue
    return {"trades": trades} if trades else None


def _ask_model_to_name(rows):
    """Group and name the register's categories. Returns [] if the model is no help."""
    from logic import local_llm

    if not local_llm.available():
        return []

    listing = "\n".join(f'{r["code"]}: {r["register_wording"]}' for r in rows)
    raw = local_llm._generate(listing, system=_GROUPING_SYSTEM, temperature=0.1,
                              timeout=local_llm.WARMUP_TIMEOUT, max_tokens=2048)
    if not raw:
        return []

    parsed = _parse_possibly_truncated(raw)
    if parsed is None:
        log.info("Discovery naming returned unusable JSON")
        return []

    # Only codes we actually asked about survive. A model that invents "47115"
    # would otherwise attach a real-looking count to a trade nobody runs here.
    allowed = {r["code"] for r in rows}
    named = []
    for item in parsed.get("trades", []):
        codes = [c for c in item.get("codes", []) if c in allowed]
        hindi, english = (item.get("hindi") or "").strip(), (item.get("english") or "").strip()
        if codes and hindi and english:
            named.append({"hindi": hindi, "english": english, "codes": codes})
    return named


def discovered_trades(pincode, limit=25, key=None):
    """
    Trades that demonstrably run in her pincode, named so she can recognise them.

    Counts, shares and codes come from the register. Only the names come from
    the model, and any code it did not receive is discarded. When there is no
    model, the register's own wording is used — clumsy, but true.
    """
    rows = candidate_trades(pincode, limit=limit, key=key)
    if not rows:
        return []

    by_code = {r["code"]: r for r in rows}
    grouped, used = [], set()

    for group in _ask_model_to_name(rows):
        codes = [c for c in group["codes"] if c not in used]
        if not codes:
            continue
        used.update(codes)
        grouped.append({
            "hindi": group["hindi"],
            "english": group["english"],
            "codes": codes,
            "count": sum(by_code[c]["count"] for c in codes),
            "share": sum(by_code[c]["share"] for c in codes),
            "register_wording": "; ".join(by_code[c]["register_wording"] for c in codes[:3]),
        })

    # Anything the model skipped still gets offered, under the register's words.
    for row in rows:
        if row["code"] in used:
            continue
        grouped.append({
            "hindi": row["register_wording"][:60],
            "english": row["register_wording"][:60],
            "codes": [row["code"]],
            "count": row["count"],
            "share": row["share"],
            "register_wording": row["register_wording"],
        })

    grouped.sort(key=lambda g: -g["count"])
    return grouped
